# Generated by Django 4.1.2 on 2022-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(choices=[('o+ve', 'o+ve'), ('o-ve', 'o-ve'), ('b+ve', 'b+ve'), ('b-ve', 'b-ve'), ('ab+ve', 'ab+ve'), ('ab-ve', 'ab-ve')], max_length=5)),
                ('Age', models.IntegerField()),
                ('Contact', models.CharField(max_length=15)),
                ('AltContact', models.CharField(blank=True, max_length=15, null=True)),
                ('Address', models.CharField(max_length=200)),
                ('permedhis', models.CharField(max_length=300)),
            ],
        ),
    ]
